export const CHEF_LIST_REQUEST = 'CHEF_LIST_REQUEST'
export const CHEF_LIST_SUCCESS = 'CHEF_LIST_SUCCESS'
export const CHEF_LIST_FAIL = 'CHEF_LIST_FAIL'

export const CHEF_DETAILS_REQUEST = 'CHEF_DETAILS_REQUEST'
export const CHEF_DETAILS_SUCCESS = 'CHEF_DETAILS_SUCCESS'
export const CHEF_DETAILS_FAIL = 'CHEF_DETAILS_FAIL'