export const CHEF_LIST_REQUEST = 'CHEF_LIST_REQUEST'
export const CHEF_LIST_SUCCESS = 'CHEF_LIST_SUCCESS'
export const CHEF_LIST_FAIL = 'CHEF_LIST_FAIL'

export const CHEF_DETAILS_REQUEST = 'CHEF_DETAILS_REQUEST'
export const CHEF_DETAILS_SUCCESS = 'CHEF_DETAILS_SUCCESS'
export const CHEF_DETAILS_FAIL = 'CHEF_DETAILS_FAIL'

export const CHEF_DELETE_REQUEST = 'CHEF_DELETE_REQUEST'
export const CHEF_DELETE_SUCCESS = 'CHEF_DELETE_SUCCESS'
export const CHEF_DELETE_FAIL = 'CHEF_DELETE_FAIL'

export const CHEF_CREATE_REQUEST = 'CHEF_CREATE_REQUEST'
export const CHEF_CREATE_SUCCESS = 'CHEF_CREATE_SUCCESS'
export const CHEF_CREATE_FAIL = 'CHEF_CREATE_FAIL'
export const CHEF_CREATE_RESET = 'CHEF_CREATE_RESET'

export const CHEF_UPDATE_REQUEST = 'CHEF_UPDATE_REQUEST'
export const CHEF_UPDATE_SUCCESS = 'CHEF_UPDATE_SUCCESS'
export const CHEF_UPDATE_FAIL = 'CHEF_UPDATE_FAIL'
export const CHEF_UPDATE_RESET = 'CHEF_UPDATE_RESET'

export const CHEF_CREATE_REVIEW_REQUEST = 'CHEF_CREATE_REVIEW_REQUEST'
export const CHEF_CREATE_REVIEW_SUCCESS = 'CHEF_CREATE_REVIEW_SUCCESS'
export const CHEF_CREATE_REVIEW_FAIL = 'CHEF_CREATE_REVIEW_FAIL'
export const CHEF_CREATE_REVIEW_RESET = 'CHEF_CREATE_REVIEW_RESET'

export const CHEF_TOP_REQUEST = 'CHEF_TOP_REQUEST'
export const CHEF_TOP_SUCCESS = 'CHEF_TOP_SUCCESS'
export const CHEF_TOP_FAIL = 'CHEF_TOP_FAIL'