export const USERRECIPE_SEND_REQUEST = 'USERRECIPE_SEND_REQUEST'
export const USERRECIPE_SEND_SUCCESS = 'USERRECIPE_SEND_SUCCESS'
export const USERRECIPE_SEND_FAIL = 'USERRECIPE_SEND_FAIL'
export const USERRECIPE_SEND_RESET = 'USERRECIPE_SEND_RESET'


export const USERRECIPE_DETAILS_REQUEST = 'USERRECIPE_DETAILS_REQUEST'
export const USERRECIPE_DETAILS_SUCCESS = 'USERRECIPE_DETAILS_SUCCESS'
export const USERRECIPE_DETAILS_FAIL = 'USERRECIPE_DETAILS_FAIL'
export const USERRECIPE_DETAILS_RESET = 'USERRECIPE_DETAILS_RESET'

export const USERRECIPE_LIST_REQUEST = 'USERRECIPE_LIST_REQUEST'
export const USERRECIPE_LIST_SUCCESS = 'USERRECIPE_LIST_SUCCESS'
export const USERRECIPE_LIST_FAIL = 'USERRECIPE_LIST_FAIL'
export const USERRECIPE_LIST_RESET = 'USERRECIPE_LIST_RESET'

export const USERRECIPE_DELETE_REQUEST = 'USERRECIPE_DELETE_REQUEST'
export const USERRECIPE_DELETE_SUCCESS = 'USERRECIPE_DELETE_SUCCESS'
export const USERRECIPE_DELETE_FAIL = 'USERRECIPE_DELETE_FAIL'
